config/routes.rb
Rails.application.routes.draw do
  resources :meetups
  resources :sessions

  root 'tests#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  resources :tests
  get '/create' => 'tests#create', as: 'create_session'
  get '/login'  => 'tests#login',  as: 'login_session'
  get '/available' => 'tests#available'
  get '/index' => 'tests#index'

  get '/test/meet' => "tests#show", as: 'login'
  get '/404' => "tests#create"

  post '/tests/new' => "tests#new"

  get 'meetups/:meetups_id/availables' => 'availables#new', as: 'availables'
  post 'meetups/:meetups_id/availables' => 'availables#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/available.rb
class Available < ApplicationRecord
  has_and_belongs_to_many :schedules
end

app/models/meetup.rb
class Meetup < ApplicationRecord
  has_many :schedules, inverse_of: :meetup

  accepts_nested_attributes_for :schedules, reject_if: :all_blank, allow_destroy: true

  # has_secure_password

  validates_presence_of   :name, :message => 'Please provide a session name', on: :create
  validates_uniqueness_of :name, :case_sensitive => false, :message => "Meetup name has already been taken", on: :create

  # validates_length_of :session_password, minimum: 8, too_short: 'please enter at least 8 characters', on: :create
  # validates_confirmation_of :session_password, on: :create
end

app/models/person.rb
class Person < ApplicationRecord

  has_and_belongs_to_many :schedules

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  
  belongs_to :meetup
  has_and_belongs_to_many :people

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/availables_controller.rb
class AvailablesController < ApplicationController
  def index
  end

  def new
    @meetup = Meetup.find(params[:meetups_id])
    # @schedules = Schedule.all.where(meetup_id: @meetup)
  end


  def create
    # render plain: params[:person].inspect

    schedules = available_params[:schedule_ids]
    @meetup = Meetup.find(params[:meetups_id])


    pax = Person.create(:person_name => available_params[:person_name])

    schedules.each { |id| if id != "" then Schedule.find(id).people << pax end }

    redirect_to @meetup

  end

  private
  def available_params
    params.require(:meetup).permit(:person_name, :schedule_ids => [])
  end

end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController
  before_action :set_meetup, only: [:show, :edit, :update, :destroy]

  # GET /meetups
  # GET /meetups.json
  def index
    @meetups = Meetup.all
  end

  # GET /meetups/1
  # GET /meetups/1.json
  def show
    # @meetups = Meetup.all
    @people = Person.all
    # @person = Person.find(1)
  end

  # GET /meetups/new
  def new
    @meetup = Meetup.new
  end

  # GET /meetups/1/edit
  def edit
  end

  # POST /meetups
  # POST /meetups.json
  def create
    # render plain: params[:session].inspect
    @meetup = Meetup.new(meetup_params)

    respond_to do |format|
      if @meetup.save
        format.html { redirect_to @meetup, notice: 'Meetup was successfully created.' }
        format.json { render :show, status: :created, location: @meetup }
      else
        format.html { render :new }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetups/1
  # PATCH/PUT /meetups/1.json
  def update
    respond_to do |format|
      if @meetup.update(meetup_params)
        format.html { redirect_to @meetup, notice: 'Meetup was successfully updated.' }
        format.json { render :show, status: :ok, location: @meetup }
      else
        format.html { render :edit }
        format.json { render json: @meetup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetups/1
  # DELETE /meetups/1.json
  def destroy
    @meetup.destroy
    respond_to do |format|
      format.html { redirect_to meetups_url, notice: 'Meetup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meetup
      @meetup = Meetup.find(params[:id])
      @meetup_id = @meetup.id
      @url = "https://meetup-scheduler.herokuapp.com/meetups/#{@meetup_id}"

      @mail = "mailto:?subject=Meetup Dates&body=Hey Friends, Fill in your available dates at #{@url}"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meetup_params
      params.require(:meetup).permit(:name, :description, :password, schedules_attributes: [:id, :date, :_destroy])
    end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def index

  end

  def create

  end

  def login

  end

  def available

  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  def index

  end

  def show
    # render plain:
    # redirect_to '/meetups/@post'
  end

  def create
  value = params[:test]["session"]
  # render plain: value
  value_password = params[:test]["password"]
  meetups = Meetup.all

      meetups.each do |meetup|
        if (meetup.id == value.to_i) || (meetup.name == value)
            # render plain: params[:test]
            route_id = meetup.id
            redirect_to "/meetups/#{route_id}" and return

        elsif (meetup.id == value.to_i) && (meetup.password) == value_password || (meetup.name == value) && (meetup.password) == value_password
            route_id = meetup.id
            redirect_to "/meetups/#{route_id}" and return
        end
      end
end

  def new

    creation = params[:dates]

    # render plain: creation
    @meetup = Meetup.new(name: params[:dates]['name'], description: params[:dates]['description'], )
    @meetup.save
    @meetup_id = @meetup.id
    # @schedule = Schedule.new(meetup_id: 25)
    # @schedule.save
    redirect_to "/meetups/#{@meetup.id}/edit"
    # redirect_to "/meetups/2/edit"

  end

  def login

  end

  def available

  end


    private

    def creation
      params.require(:meetup).permit(:name, :description, :password, schedules_attributes: [:id, :date, :_destroy])

      params.require(:schedule).permit(:date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/availables_helper.rb
module AvailablesHelper
end

app/helpers/meetups_helper.rb
module MeetupsHelper
end

app/helpers/new_tests_helper.rb
module NewTestsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/availables/new-old.html.erb
<h1><%= @meetup.name %></h1>

<%= form_with scope: :available, url: availables_path, local: true do |form| %>
	<p>
		<%= form.label :partcipant_name %>
		<%= form.text_field :person_name %>
	</p>

	<% @meetup.schedules.each do |schedule| %>
		<%= fields_for "available[schedule_ids][]", schedule do |available_fields| %>
			<%= schedule.date %><%= available_fields.check_box :id%>
		<% end %>
	<% end %>

	<p>
		<%= form.submit 'Submit Participation'%>
	</p>
<% end %>

app/views/availables/new.html.erb
<body class="availables-page">
	<div class="availables-start">
		<h3>Add in Name and Availability </h3>

		<%= form_with scope: :meetup, url: availables_path, local: true do |form| %>

		<div class="form-row">
			<div class="col-md-12">
			<p>
				<%= form.label :partcipant_name %>
				<%= form.text_field :person_name, :class => "form-control", placeholder: "Eg. Susan Chan" %>
			</p>
			</div>
		</div>
			<div class="form-row check-boxes">
				<%= form.collection_check_boxes :schedule_ids, @meetup.schedules, :id, :date do |b| %>
        <%= b.label class:"label-checkbox col-md-4" do%>
         <%=b.check_box :data => { :toggle => 'toggle', :on => "Yes", :off => "No", :onstyle => "success", :offstyle => "danger" }  %>

<!--          http://www.bootstraptoggle.com/ -->
<!-- https://stackoverflow.com/questions/32510159/implementing-bootstrap-toggle-switch
 THANK YOU JOHNSORRENTINO T_T -->
         <%=b.text %>
        <%end%>
				<% end %>
			</div>



			<div class="form-row"></div>
		  <p>
			<%= form.submit "Add Name", :class => "btn btn-primary btn-block" %>
		  </p>
		  </div>
		<% end %>
		</div>
	</div>
</body>

app/views/availables/old_new.html.erb
<body class="available-page">
    <div class="available-start">
        <h1><%= @meetup.name %></h1> <br>

				<%= form_with scope: :available, url: availables_path, local: true do |form| %>
				<table class="table">
				  <thead class="">
				    <tr class="table-row">
				    	<th scope="col">Your Name</th>
				    	<%= @schedules.each do |schedule| %>
				    		<th scope="col"><%= schedule.date %></th>
				    	<% end %>
				    </tr>
				  </thead>

				  <tbody>
				    <tr class="table-row">
				      <th scope="row"><%= form.text_field :person_name %></th>
				    		<td><%= form.collection_check_boxes :available, @schedules, :id, :date %></td>
				    </tr>
				  </tbody>
				</table>

				<div class="actions">
					<%= form.submit %>
				</div>

				<% end %>

		</div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetupScheduler</title>
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat%7COswald" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag asset_path('calendar.png') %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/meetups/_form.html.erb
	<%= form_with(model: meetup, local: true) do |form| %>
	  <% if meetup.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(meetup.errors.count, "error") %> prohibited this meetup from being saved:</h2>

	      <ul>
	      <% meetup.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="form-row">
		  <div class="field col-md-6">
		    <%= form.label :name %>
		    <%= form.text_field :name, :class => "form-control" %>
		  </div>


		  <div class="field col-md-6">
		    <%= form.label :description %>
		    <%= form.text_field :description, :class => "form-control" %>
		  </div>
	  </div>

	  <h3>Proposed Dates</h3>
	  <div id="schedules">
	  	<%= form.fields_for :schedules do |schedule| %>
	      <%= render 'schedule_fields', :f => schedule %>
	    <% end %>
	    <div class='links proposed-dates'>
	    	<br>
	      <p><%= link_to_add_association 'Click Here To Add Date', form, :schedules, :class => "btn btn-block btn-primary btn-add" %>
	    </div>
	  </div>
	  <br>
	  <div class="actions">
	    <%= form.submit :class => "btn btn-lg btn-block update-date-btn"%>
	  </div>
	<% end %>

app/views/meetups/_schedule_fields.html.erb
<div class="form-row">
<div class='nested-fields col-md-12'>
  <div class="field">
    <%# f.label :date %>
    <%= f.text_field :date, :data => {:provide => "datepicker", :date_format => "yyyy/mm/dd", :date_start_date => "2019/05/09", :date_autoclose => true}, :class => "form-control" %>
  </div>
  <%= link_to_remove_association "Remove Date", f, :class => "btn btn-block btn-danger" %>
</div>
</div>

app/views/meetups/edit.html.erb
<body class="meetup-edit">
<div class="meetup-edit-form">
<h1>Select Meetup Dates</h1>

<%= render 'form', meetup: @meetup %>

<%# link_to 'Show', @meetup %>
<%# link_to 'Back', meetups_path %>
</div>

</body>

app/views/meetups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetups.each do |meetup| %>
      <tr>
        <td><%= meetup.name %></td>
        <td><%= meetup.description %></td>
        <td><%= meetup.password %></td>
        <td><%= link_to 'Show', meetup %></td>
        <td><%= link_to 'Edit', edit_meetup_path(meetup) %></td>
        <td><%= link_to 'Destroy', meetup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meetup', new_meetup_path %>

app/views/meetups/new.html.erb
<h1>New Meetup</h1>

<%= render 'form', meetup: @meetup %>

<%= link_to 'Back', meetups_path %>

app/views/meetups/show.html.erb
<body class="meetup-show">
<div class="meetup-show-page">
<p id="notice"><%= notice %></p>

<div class="row">
<h1 class="col-md-12">
  <strong>Name:</strong> <span class="meetup-highlight"> <%= @meetup.name %> </span>
</h1>

<h1 class="col-md-12">
  <strong>Description:</strong> <span class="meetup-highlight"> <%= @meetup.description %> </span>
</h1>

</div>
<h2>
  <strong>Proposed Dates:</strong>
  <br><br>
<!--   <ul> -->
		  	<div class="row">
			  	<% @meetup.schedules.order(:date).each do |schedule| %>
				  		<div class="col-md-4">
				  			<img src="/calendar2.png" alt="calendar" class="calender-img" />
				      	<p><%= schedule.date.split("/").reverse.join("/") %></p>

				      	<% schedule.people.each do |person| %>
									<p><%= person.person_name %></p>
								<% end %>
							</div>
			    <% end %>
    	   </div>
<!--   </ul> -->
</h2>



<div class="row">
	<div class="col-md-4">
		<p> <%= link_to 'Edit Dates', edit_meetup_path(@meetup), :class => "btn btn-lg btn-block edit-date-btn" %> </p> <!-- | -->
	</div>

	<div class="col-md-4">
		<p> <%= link_to 'Add Availability', availables_path(@meetup), :class => "btn btn-lg btn-block edit-name-btn" %> </p>
	</div>

	<div class="col-md-4">
		<p> <%= link_to 'Ping Your Friends', @mail, :class => "btn btn-lg btn-block btn-mailer" %> </p>
	</div>
</div>
<%# link_to 'Back', meetups_path %>



<br><br>
<a href="/index"> <p> Return to Index Page</p>  </a>
</div>
</body>

app/views/schedules/available.html.erb
<body class="available-page">
    <div class="available-start">
        <h1> INSERT ACTIVITY THINGY HERE </h1> <br>


<table class="table">
  <thead class="">
    <tr class="table-row">
      <th scope="col"></th>
      <th scope="col">6 May 2019</th>
      <th scope="col">7 May 2019</th>
      <th scope="col">8 May 2019</th>
    </tr>

<!--     <tr class="table-row">
      <th scope="col">Count</th>
      <th scope="col">1</th>
      <th scope="col">2</th>
      <th scope="col">3</th>
    </tr> -->

  </thead>
  <tbody>
    <tr class="table-row">
      <th scope="row">Chang</th>
      <td>⭕</td>
      <td></td>
      <td>⭕</td>
    </tr>
    <tr class="table-row">
      <th scope="row">Kai</th>
      <td></td>
      <td>⭕</td>
      <td>⭕</td>
    </tr>
    <tr class="table-row">
      <th scope="row">Brother</th>
      <td>⭕</td>
      <td></td>
      <td>⭕</td>
    </tr>
  </tbody>
</table>


<h3>The date where most people are available is...<span style ="color: #1B9AAA"> 8 May 2019 </span></h3>
    </div>


    <%# rand.to_s[2..5] %>
</body>

app/views/schedules/create.html.erb
<body class="create-page">
    <div class="create-start">
        <h1>CREATE MEETUP!</h1> <br>
<!--         <button type="button" class="btn btn-lg btn-block create-btn">CREATE</button>
        <button type="button" class="btn btn-lg btn-block login-btn">LOGIN</button> <br> -->

        <form>
          <div class="form-group">
            <label for="exampleInputEmail1"> <h3>Session ID </h3></label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter Session ID">
          </div>

          <div class="form-group">
            <label for="exampleInputPassword1"><h3>Password(Optional) </h3></label>
            <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
          </div>

          <div class="form-group">
            <label for="exampleInputPassword1"><h3> Description</h3></label>
<!--             <input type="textarea" rows="5" class="form-control" id="exampleInputPassword1" placeholder="Activity"> -->
              <textarea class="form-control" rows="3" id="comment"></textarea>
          </div>

          <button type="submit" class="btn btn-lg btn-block login-btn">Create</button>
        </form>

    </div>


    <%# rand.to_s[2..5] %>
</body>

app/views/schedules/index.html.erb
	<body class="index-page">
		<div class="index-start">
			<h1>Meetup Scheduler!</h1> <br>
			<button type="button" class="btn btn-lg btn-block create-btn"> <%= link_to 'CREATE NEW SESSION', create_session_url %>  </button>
			<button type="button" class="btn btn-lg btn-block login-btn"><%= link_to 'LOGIN EXISTING SESSION', login_session_url %> </button> <br>
		</div>
	</body>